-----
11June2020
-----


# 11June2020 Incubator Documentation 24well plates


### Dish A from 2June2020


9June2020 is 7 dpf, n=43
From which 7 died and sampled, 8 were taken to "poor" plate, rest left. 
10June2020 eve, n=39


Today I replaced water and counted $n=38$.
1 detail was moved to small dish for poor A larvae (new) (Movie_453.avi) plate markings: 


-----
A 11June2020 Poor details
n=1
-----




### Dish B From 2June2020:


Offspring tracking.
9June2020 dfp = 7, n = 28
10June2020 dpf = 8, n = 27
10 "poor" details were separated to plate B.








Easy peasy no one showed any lack of money.
1 dead on lid, taken to new strip S1 at position 1
| 1                          | 2 | 3 | 4 | 5 | 6 | 7 | 8 |
|----------------------------+---+---+---+---+---+---+---|
| 11.6 From big dish B (2.6) |   |   |   |   |   |   |   |


### Big dish C From 3June2020


Cross +/- X +/- from #6
9june2020 6dpf n=54




11june2020 - n=48 (reafirm)
fed and water replaced




### 24plate B:


### no.55 from 8june2020
9june n=55
10june n=39
11june:
n=39
no gfp


### no.48 from 8june2020
n=60
9june =55
10june n=55
11june:
n=55


### inj3 09june2020


09june n= 38
09june n=31
10june n=25
11june:
n=23


2 details look really poor were separated


### inj3 control (no injection) no.79 9june2020
n0=79
9june n=7
10jun n=6
11june all still in chorion, n=6


### inj2 8june2020
n0=38
11june2020 n=
21


## inj2 control 8june2020
n0 = 10
11june n=8

\pagebreak{}{}

