# 16July2020 zFish Talk:

---------
16July2020
---------

**First and foremost:**   
[Addgene blog on frankenbodies](https://blog.addgene.org/ha-frankenbody-a-new-imaging-tool-to-visualize-single-molecules-and-nascent-peptides)  
[Addgene Plasmid order page - FB](https://www.addgene.org/browse/article/28203855/)  

**Secondly:**

Today we discussed the directions and path of my research.

**DNA level:**  
As I came up with some issues with my injections, you suggested me to make some
adjustments to my injection mix from HD template concentration to injection volume adjustment.
Furthermore, I will look into more options for using enhancer and inhibitor materials including
the ones in our lab.  

**Protein level:**  
I got green light on the frankenbodies (FB), and as we discussed the immediate phase is
to check FB's activity in zebrafish (ZF) with a "dud" protein from Avi's HA tagged protein plasmid.
To do so I will have to inoculate the plasmid in e-coli, T7 transcribe it *in-vitro* and
finally inject both FB mRNA and Avi's HA tagged protein. The end result is specific illumination
of the HA tagged plasmid. After that we can go shenanigans and construct different GNE mutant HA
tagged protein plasmids, then onwards to inject KO ZF.

*ZF KO rescue:* First thing needed to be examined is if hGNE^wt^ can actually rescue KO ZF.
I need to either acquire hGNE^wt^ containing plasmid or construct one. After acquisition of hGNE^wt^
will inject KO ZF and proceed to examine dead~tf~-dead~ti~ between KO injected and KO un-injected. If
KO injected with hGNE~wt~ we can conclude that hGNE can rescue and thus we can use it to perform
recombinant protein injections.

*FB highlight:* The highlight of the frankenbodies will be finally verified one we can visualize the
protein in gel or western using fluorescent assay. (IF) After which we can proceed to examine PTM on
the protein. Furthermore, we can see, *in-vivo* if the protein aggregates in tissues. 

Lastly, after fluorescence is achieved *in-vivo* using FB, we can examine how long the proteins
last in the tissue, if mutations cause change in λ of the protein; if epimerase mutations rescue
and if only epimerase part of the GNE can rescue.

**Metabolite level:** 

```
if t>=365/2 TRUE
else
FALSE
```

` END OF TRANSMISSION `

