# 27July2020 Frankenbodies plasmid arrival, streaking cultures

----
27July2020
----

The following frankenbody plasmids (FB) arrived in an *E. coli* cell culture on LB agar media:

[Addgene FB main](https://www.addgene.org/browse/article/28203855/ ) 

1. [pET23b-15F11-HA-mEGFP-6xHis](https://www.addgene.org/129593/) - **ALIASES**: "gHi6", "FBgfpHis"
2. [pCMV-15F11-HA-mEGFP](https://www.addgene.org/129590/) - **ALIASES**: "FBgfp", "gfp" 
3. [pCMV-15F11-HA-mCh](https://www.addgene.org/129591/) - **ALIASES**: "FBmCh", "mCh"

For local plasmid sequences see:

1. [pET23b-15F11-HA-mEGFP-6xHis](sequences/pET23b-2E2-HA-mEGFP-6xHis.gbk)
2. [pCMV-15F11-HA-mEGFP](sequences/pCMV-15F11-HA-mEGFP.gbk)
3. [pCMV-15F11-HA-mEGFP](sequences/pCMV-15F11-HA-mEGFP.gbk)


# 27July2020 Procedure: colony streaking of arrived frankenbody plasmids colonies

Following the protocol...

## Day 1 27July2020 
I prepared the biological hood at the second floor large chemistry laboratory.
Taken an ampicilin work solution from preparation room and diluted by 0.175.
After which I smeared 7 LB agar plates with 200 µl diluted ampicilin with beads:  
2 for FBmCh, 2 for FBgfp, 2 for FBgfp6xHis and 1 for control, had another plate with nothing on it for negative control as well, total 7 plates.
I touched the center of the Frankenbodies initial agar tube at the center of its poke hole and streaked the corresponding plates. My smearing was a bit rough and I scarred the agar.
Finally I placed the used blue sticks inside a 5 ml liquid LB and incubated the plates and liquid broth at 37°C overnight.

## Day 2 28July2020

The plates did provide colony isolation for FBgfp6xHis, although none grew on FBmCh or FBgfp. The reason why, is that I used ampicilin although the plasmids only had kanamycin resistance. Negative control showed no growth. The FBgfp underwent isolated colony liquid broth culturing overnight. The FBgfp6xHis liquid broth from the day before was glycerol stocked at -80°C fridge at the preparation room of the second floor ([See inventory file from 28 July](tables/inventory.ods)).

New cultures for FBgfp and FBmCh were prepared using kanamycin, 2 plates each incubated overnight.

## Day 3 29July2020

FBgfp and FBmCh isolation plates showed single colonies which were then transferred to liquid broth overnight.

Plasmid isolation for FBgfp6xHis was performed according to manufacturer protocol (promega - Wizard Plus SV minipreps DNA purification system - A1330).


## Day 4 30July2020

FBgfp and FBmCh isolated colonies were glycerol stocked ([See inventory file from 28 July](tables/30july2020_inventory.ods)).
I used the delivered FB agar tubes for new MIX colony liquid growth overnight to preserve the FB state as close to ordered. By MIX I mean I swabbed the blue stabby thing inside the tubes and ripped the agar apart and then dumped the blue stabby thingy in a liquid LB broth overnight.
 
Plasmid isolation for FBgfp and FBmCh was performed according to manufacturer protocol (promega - Wizard Plus SV minipreps DNA purification system - A1330).
I also performed second elution for each, using 20µl nuclease free water. [Results are shown for all plasmids in linked file](tables/Nanodrop_plasmid_elution_results.ods).

## Day 5 31July2020

Glycerol stocked the mix cultures, see inventory file.

[For final inventory outlook check this file](tables/30july2020_inventory.ods).

# 04Aug2020 - pCMV-15F11-HA-mCh: Figuring out how to make it go IVT

* Made a presentation with my workflow /home/tiriyon/TB/0MSc/ThesisNotebook/TomeOfKnowledgeV1.1/365/04Aug2020/pCMV-15F11-HA-mCh_IVTplaning  
* Added T7 promoter sequence file  
* Added pGEM-t-easy sequence file with mapping  
* Added UGENE project file ../../365/04Aug2020/mCh_T7_insertion.uprj  

# Thursday to 09Aug2020 - pcDNA3.1-DNM1-HA plasmid transfection and cloning

# 10Aug2020 - Dynamin-HA plasmid digestion

# [Streaking](https://en.m.wikipedia.org/wiki/Streaking_(microbiology)) colony isolation:

-----
Written on 27July2020
-----

## Materials:

• 2x Agar LB plates per culture.  
• 1x Agar LB plate for negative control.  
• 1x Agar LB plate for negative control + antibiotic (per each antibiotic used).  
• Ethanol 70% 0.5-1 L bottle for sterilization.   
• 50 ml falcon tubes.   
• Stative for 50 ml Falcon tubes (sterile).   
• 1.5 µl ependorf tubes (sterile).   
• Colony lifting sticks (ble ones, sterile).   
• Liquid LB.   
• Sterile glass beads.   
• Freezing tubes.   

(materials to be prepared: 50% glycerol, Ampicilin, kanamycin, liquid LB)

**Incubators initiation:**

Turn on solid incubator at 37 degrees Celsius 

## Biological hood preparation:

1. Pour 70% ethanol everywhere in the hood and wipe (not fully) with paper towel. 
2. Close window and turn UV light for 30 min. 
3. Open hood to working position and let blow for 5-15 min untill ready. 

## Antibiotics preparations:

**Ampiceline:** 100mg/ml workink stock. Prepare working stock as follows:

| material        | VOLUME/MASS | conc      |
| --------------- | ----------  | --------  |
| AMP             | 1000mg      |           |
| ddw             | 10 ml       |           |
| final           |             | 100 mg/ml |

1. Weigh ampiceline powder. 
2. Pour ddw to weighing bowl. 
3. Mix with 10 ml new seringe. 
4. Move to biological ready hood. 
5. Open new 0.2 filter. 
6. Filter solution through 0.2 filter using the syringe. 
7. Pour to marked 1.5 ependorf tube. 

**Ampicilin dilution for Agar plate:**  
**Dilution factor of 0.175**; e.g: 35 µl ampicilin on 165 µl DDW (200 µl final volume, 17.5 mg/µl).

**Kanamycin:** 50mg/ml workink stock. Prepare working stock as follows:

| material        | VOLUME/MASS | conc     |
| --------------- | ----------  | -------- |
| KANA            | 500mg       |          |
| ddw             | 10 ml       |          |
|                 |             | 50 mg/ml |

1. Weigh kanamycin powder. 
2. Pour ddw to weighing bowl. 
3. Mix with 10 ml new syringe. 
4. Move to biological ready hood. 
5. Open new 0.2 filter. 
6. Filter solution through 0.2 filter using the syringe. 
7. Pour to marked 1.5 ependorf tube. 

**Kanamycin dilution for Agar plate:**  
**Dilution factor of 0.175**; e.g: 35 µl Kanamycin on 165 µl DDW (200 µl final volume, 8.75 mg/µl).


## Plate preparation:

1. Using sterile glass beads (5-10) smear 200 µl antibiotic for 2xplates per culture using the right antibiotics (The 0.175 factorized solution not the direct work solution!). 
2. Move plate in straight motions to smear the antibiotic onto the agar. 
3. Place plate lid closed and facing up (agar towards gravital force) in preheated
incubator at 37 Celsius degrees. 

## Streaking:

Inside a prepared biological hood.

1. With blue stick, stab initial culture. 
2. Streak lightly and in zigzaggy lines the corresponding new plate with the stabby end of the blue stick. 
3. with new stabby stick streak again from the end of the zigzaggy first line in a new direction.
4. Repeat 3 until the entire plate area is streaked.
5. Incubate overnight at 37 Celsius degrees lid facing floor (agar towards cosmic rays).
6. For controls, streak with new blue stabby sticks and incubate.

## Colony isolation

Inside a prepared biological hood.

1. Fill 50 ml tubes with 15 ml LB per each seeded plate.
2. Add corresponding work solution of antibiotic - 1µl antibiotics per each ml of broth.
3. Touch a well isolated colony with blue poky thing and transfer to corresponding tube.
4. Incubate overnight at 37 Celsius degrees.

## Glycerol stock

Inside a prepared biological hood.

1. Fill 0.5 ml 50% glycerol stock in freezing tube.
2. Transfer 0.5 ml of liquid culture to corresponding freeze tube containing 0.5 50% glycerol.
3. Store at -80 Celsius degrees fridge.




# [Streaking](https://en.m.wikipedia.org/wiki/Streaking_(microbiology)) colony isolation:

-----
Written on 27July2020
-----

## Materials:

• 2x Agar LB plates per culture.  
• 1x Agar LB plate for negative control.  
• 1x Agar LB plate for negative control + antibiotic (per each antibiotic used).  
• Ethanol 70% 0.5-1 L bottle for sterilization.   
• 50 ml falcon tubes.   
• Stative for 50 ml Falcon tubes (sterile).   
• 1.5 µl ependorf tubes (sterile).   
• Colony lifting sticks (ble ones, sterile).   
• Liquid LB.   
• Sterile glass beads.   
• Freezing tubes.   

(materials to be prepared: 50% glycerol, Ampicilin, kanamycin, liquid LB)

**Incubators initiation:**

Turn on solid incubator at 37 degrees Celsius 

## Biological hood preparation:

1. Pour 70% ethanol everywhere in the hood and wipe (not fully) with paper towel. 
2. Close window and turn UV light for 30 min. 
3. Open hood to working position and let blow for 5-15 min untill ready. 

## Antibiotics preparations:

**Ampiceline:** 100mg/ml workink stock. Prepare working stock as follows:

| material        | VOLUME/MASS | conc      |
| --------------- | ----------  | --------  |
| AMP             | 1000mg      |           |
| ddw             | 10 ml       |           |
| final           |             | 100 mg/ml |

1. Weigh ampiceline powder. 
2. Pour ddw to weighing bowl. 
3. Mix with 10 ml new seringe. 
4. Move to biological ready hood. 
5. Open new 0.2 filter. 
6. Filter solution through 0.2 filter using the syringe. 
7. Pour to marked 1.5 ependorf tube. 

**Ampicilin dilution for Agar plate:**  
**Dilution factor of 0.175**; e.g: 35 µl ampicilin on 165 µl DDW (200 µl final volume, 17.5 mg/µl).

**Kanamycin:** 50mg/ml workink stock. Prepare working stock as follows:

| material        | VOLUME/MASS | conc     |
| --------------- | ----------  | -------- |
| KANA            | 500mg       |          |
| ddw             | 10 ml       |          |
|                 |             | 50 mg/ml |

1. Weigh kanamycin powder. 
2. Pour ddw to weighing bowl. 
3. Mix with 10 ml new syringe. 
4. Move to biological ready hood. 
5. Open new 0.2 filter. 
6. Filter solution through 0.2 filter using the syringe. 
7. Pour to marked 1.5 ependorf tube. 

**Kanamycin dilution for Agar plate:**  

**Dilution factor of 0.175**; e.g: 35 µl Kanamycin on 165 µl DDW (200 µl final volume, 8.75 mg/µl).


## Plate preparation:

1. Using sterile glass beads (5-10) smear 200 µl antibiotic for 2xplates per culture using the right antibiotics (The 0.175 factorized solution not the direct work solution!). 
2. Move plate in straight motions to smear the antibiotic onto the agar. 
3. Place plate lid closed and facing up (agar towards gravital force) in preheated
incubator at 37 Celsius degrees. 

## Streaking:

Inside a prepared biological hood.

1. With blue stick, stab initial culture. 
2. Streak lightly and in zigzaggy lines the corresponding new plate with the stabby end of the blue stick. 
3. with new stabby stick streak again from the end of the zigzaggy first line in a new direction.
4. Repeat 3 until the entire plate area is streaked.
5. Incubate overnight at 37 Celsius degrees lid facing floor (agar towards cosmic rays).
6. For controls, streak with new blue stabby sticks and incubate.

## Colony isolation

Inside a prepared biological hood.

1. Fill 50 ml tubes with 15 ml LB per each seeded plate.
2. Add corresponding work solution of antibiotic - 1µl antibiotics per each ml of broth.
3. Touch a well isolated colony with blue poky thing and transfer to corresponding tube.
4. Incubate overnight at 37 Celsius degrees.

## Glycerol stock

Inside a prepared biological hood.

1. Fill 0.5 ml 50% glycerol stock in freezing tube.
2. Transfer 0.5 ml of liquid culture to corresponding freeze tube containing 0.5 50% glycerol.
3. Store at -80 Celsius degrees fridge.


------
19Aug2020
------

# PFA whole -mount larvae fixation

## Materials:

* 4% PFA
* 50ml Falcon tube

## Procedure:

1. Fill 50ml tube with larvae and embryo water, place in ice until larvae sink.
2. Remove liquid carefully to not lift larvae.
3. Fill 10ml PFA 4%.


# HIT-Dh5α High 10^8^ Cat.No: RH618 by real-biotech 
<a name="HITtransfer"></a>
[Man Protocol for HIT-Dh5α High 10^8^ Cat.No: RH618 by real-biotech](http://www.real-biotech.com/index.asp?modules=product&files=p2&ID1=153)

## Materials:

* Biological sterile hood
* Ice bucket
* 37°C plating beads
* Selective plates (*e.g.* with antibiotic)
* Kit components (1 tube of bacteria)
* DDW
* 1.5 ml tubes
* Antibiotics (Kana/Amp)

## Procedure:

### Antibiotics preparations:

**Ampiciline:** 100mg/ml working stock. Prepare working stock as follows:

| material        | VOLUME/MASS | conc      |
| --------------- | ----------  | --------  |
| AMP             | 1000mg      |           |
| ddw             | 10 ml       |           |
| final           |             | 100 mg/ml |

1. Weigh ampiceline powder. 
2. Pour ddw to weighing bowl. 
3. Mix with 10 ml new seringe. 
4. Move to biological ready hood. 
5. Open new 0.2 filter. 
6. Filter solution through 0.2 filter using the syringe. 
7. Pour to marked 1.5 ependorf tube. 

**Ampicilin dilution for Agar plate:**  
**Dilution factor of 0.175**; e.g: 35 µl ampicilin on 165 µl DDW (200 µl final volume, 17.5 mg/µl).

**Kanamycin:** 50mg/ml workink stock. Prepare working stock as follows:

| material        | VOLUME/MASS | conc     |
| --------------- | ----------  | -------- |
| KANA            | 500mg       |          |
| ddw             | 10 ml       |          |
|                 |             | 50 mg/ml |

1. Weigh kanamycin powder. 
2. Pour ddw to weighing bowl. 
3. Mix with 10 ml new syringe. 
4. Move to biological ready hood. 
5. Open new 0.2 filter. 
6. Filter solution through 0.2 filter using the syringe. 
7. Pour to marked 1.5 ependorf tube. 

**Kanamycin dilution for Agar plate:**  

**Dilution factor of 0.175**; e.g: 35 µl Kanamycin on 165 µl DDW (200 µl final volume, 8.75 mg/µl).

### Plate prep:

1. Using sterile glass beads (5-10) smear 200 µl antibiotic for a plates per culture using the right antibiotics (The 0.175 factorized solution not the direct work solution!). 
2. Move plate in straight motions to smear the antibiotic onto the agar. 
3. Place plate lid closed and facing up (agar towards gravital force) in preheated
incubator at 37 Celsius degrees. 

### Transfer:

1. Prepace ice bucket, 37°C plating beads and incubator.
2. Thaw competent cell vial with RT until $\frac{1}{3}$~$\frac{1}{2}$ thawed.
3. Add DNA whose volume is **less than 5%** of cell volume, vortex 1s.
4. Place on ice for 1~10 min.
5. Transfer onto 37°C dry selection plate media, spread using pre-heated beads.
6. Incubate **immediately** at 37°C for 16~18h.
